name: Pipeline for ML Model Training

on:
  push:
    branches:
      - base

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: Test model
        run: python3 main.py

      - name: Display training result
        run: cat accuracy.txt
